language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
  - touch _static/.nojekyll
  - mv favicon.ico _static/favicon.ico

deploy:
  provider: pages
  local_dir: _static
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master